### ISSUE TITLE
后台导入学校数据，学生家长卡

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#101]
前端通讯录查不到卡号，具体问华总

**Comment by yang55** [comment]
这个问题需要廖强那边在导入时，如果导入数据的时候就将ic卡一起绑定到学生或者家长的头上，那么就要进行tb_ic_card表的操作，将绑定的卡在ic卡表的学校改为导入数据的学校，这个问题已经很久以前就提出了这个解决方案了 。
