### ISSUE TITLE
删除班级后，班级里面小朋友绑定的卡的绑定关系没有解除

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#102]
删除班级后，班级里面小朋友绑定的卡的绑定关系没有解除，这张卡还是用不了

**Comment by yang55** [comment]
经过查询，被删除了的班级下面的学生如果被删除了，不管ic卡是否与该班级的学生绑定，只要学生的删除状态为1，那么该ic卡就可以重新进行绑定到别的学生，如何没有删除，那么，就是删除班级的代码出现问题。经过查询，通讯录的删除班级，会将班级下面的学生，以及学生家长和学生家长对应的学校家长删除，不会出现ic卡无法绑定的问题

**Comment by yang55** [comment]
还有一种情况，删除时，删除学生，家长以及学校家长不成功，导致ic卡不能绑定，如果是学生卡，只要学生被删除就能重新绑定，如果是家长卡，只要家长被删除就能重新绑定，和学校家长没有直接联系。
