### ISSUE TITLE
视频授权已经开通还是看不了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#112]
![wechatimg680](https://user-images.githubusercontent.com/24886936/30359426-368b0be8-987d-11e7-8b14-ca0bb9406aa4.jpeg)
![wechatimg681](https://user-images.githubusercontent.com/24886936/30359427-368ce0c6-987d-11e7-9388-52229c796c18.jpeg)
![wechatimg679](https://user-images.githubusercontent.com/24886936/30359428-3698df8e-987d-11e7-92db-214f00cc0d78.jpeg)

**Comment by yang55** [comment]
其中一个孩子没有视频授权，但是家长进入通讯录默认选择的孩子刚好是没有授权的哪一个。
