### ISSUE TITLE
学校后台视频管理付费授权里面，班级学生显示人数不对

### ISSUE THREAD

**Issue by veraGe** [didanoDevelopers2017/didano-platform-base#125]
估计是付费授权里面将deleted = 0的小朋友一起查出来了。
以安琪儿学校为列，school_id = 11， 除开测试班级class_id = 64, 一个有602个下朋友。但是付费授权中，已授权的小朋友就有703个，远超过总人数。但是通过sql查出来，开通小朋友只有186个

**Comment by stephenwang2017** [comment]
select a.* from tb_student a ,vd_auth_switch b where a.school_id=11 and a.deleted=0 and b.owner_type=1 and b.owner_id=a.id and b.is_use=1

**Comment by stephenwang2017** [comment]
已经修复
