### ISSUE TITLE
宝贝中心的宝贝生日和通讯录里显示的小朋友生日不一样

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#75]
需要核实

**Comment by yang55** [comment]
@JsonFormat(pattern="yyyy-MM-dd"）转换时间格式时默认的时间：GMT(格林威治标准时间)，改为@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")   GMT+8时间(即中国所在时区的时间)即可。
