### ISSUE TITLE
通讯录绑定有问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#91]
当绑定一个家长一个小朋友，包括小朋友卡号，家长卡号，一次绑定，绑定报错，但是分开绑定ok

**Comment by yang55** [comment]
经过测试，同时绑定学生以及家长的ic卡没有问题，在代码上面，也没有冲突。学生卡的绑定和家长卡的绑定是分步进行的，不管是添加还是修改学生信息，都是先将学生的信息添加/修改，在进行家长信息的添加/修改。两个部分并不冲突。具体的情况进过测试，没有问题。
