### ISSUE TITLE
何海燕老师的信息昨天还在，今天就不在了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#98]
何海燕老师的信息昨天还在，今天就不在了，我刚才给绑好。何海燕，15028233769，具体，联系唐迈

**Comment by underhill6** [comment]
1. 查询数据库，何老师有三次绑定记录，一次绑定家长，两次绑定老师，出问题的地方是绑定教职工老师的部份；
2.何老师第一次绑定老师，现在deleted已经被置为1（已删除）:
   A. 第一次添加老师数据到tb_staff是在8月30下午4点33分，tb_staff表id是1277，更新时间显示为8月31日早上2点01分;
   B.tb_staff表更新trigger记录的删除更新时间是8月31日下午1点04分；
   C.tb_user表更新时间显示为8月30日下午5点38分;
3.何老师第二次绑定是在9月01日12点38分，绑定成功,staff_id是1582；
